#!/usr/bin/env bash

PY="ipython"
MOD="uberfuzz"
CMD="$PY -m $MOD --"

OPTS="$@"
if [ "$OPTS" = "" -o "$OPTS" = "-h" ]; then
  $CMD -h
  exit $?
fi

printf "[+] Running command: $CMD"
printf " %q" "$@"
printf "\n"
$CMD "$@"
